// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixgrndsmvilfrbnfmbzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4Z3JuZHNtdmlsZnJibmZtYnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTE3NjUsImV4cCI6MjA3Mzc2Nzc2NX0.gOYYZzgIrQlx6ylFhEpXyNnMrOL7-U5rV1dHeLKBCnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});